# Generated by Django 2.2.5 on 2019-10-15 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='KeyFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_frame', models.IntegerField()),
                ('value', models.FloatField()),
                ('interpolator', models.CharField(choices=[('linear', 'Linear'), ('easy_in', 'Easy In'), ('easy_out', 'Easy Out'), ('easy_ease', 'Easy Ease')], default='linear', max_length=9)),
                ('animation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyframes', to='animations.Animation')),
            ],
        ),
    ]
