# Generated by Django 2.2.5 on 2019-10-23 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
                ('animationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animations.Animation')),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dislike', models.IntegerField()),
                ('animationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animations.Animation')),
            ],
        ),
    ]
